### ISSUE TITLE
RER C

### ISSUE THREAD

**Issue by damoun** [Opaze/OpenJabNab#1]
Bonjour

Serait-il possible d'inclure le RER C ? Même si les terminus sont assez galère.

**Comment by Opaze** [comment]
Bonjour,

Dans l'tat actuelle des choses ce n'est pas possible facilement, car le
plugin rcupre les donnes depuis le site de la RATP.
Et le site de la RATP ne donne que les informations pour les RER A, B et le
C est gr par la SNCF.

Nanmoins, je vais regarder pour inclure les donnes de la SNCF (Uniquement
rgion parisienne) dans un prochain commit.
En esprant que les donnes soient faciles  rcuprer.

F.

2011/12/20 Damien <
reply@reply.github.com
